###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://sap.github.io/jenkins-library/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###

### General project setup
general:
  inferBuildTool: true
  buildTool:"mta":

### Step-specific configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14

  artifactPrepareVersion:
    versioningType: cloud_noTag

  npmExecuteLint:
    failonError:true

  cloudFoundryDeploy:
    mtaDeployParameters:"-f --version-rule ALL"

  tmsUpload:
    nodeName:"dev"
    credentialsId:"tms-sk"  #credentials from cicd 

### Stage-specific configuration
stages:
  Build:
    mavenExecuteStaticCodeChecks: true #false
    npmExecuteLint:true:

  Additional Unit Tests:
    npmExecuteScripts:true 
    karmaExecuteTests:true 

  'Confirm':
    manualConfirmation: true  #false

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

  Acceptence:
    cloudFoundryDeploy:false
    cfApiEndpoint:'https://https://api.cf.us10-001.hana.ondemand.com'
    cfOrg:"ab4767b0trial"
    cfSpace:"dev"
    cfAppName:"app"
    cfCrendetialsId:"deploy-to-cf"
    uiVeri5ExecuteTests:false
  #pooja 
  Release:
    cfTargets:
      - org: 'ab4767b0trial'
        space: 'dev'
        apiEndpoint: 'https://https://api.cf.us10-001.hana.ondemand.com'
        #appname from cicd job name
        appName: 'app'
        manifest: 'manifest.yml'
        #credential from cicd  credentials
        credentialsId: 'tms-sk'
        tmsUpload:'true':
